# -*- coding: utf-8 -*-
"""atividade 13.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_-O2d6AvEL5SVnoPwI-dTJjrKBAvchaa
"""

class SaldoInsuficienteError(RuntimeError):
    pass

class Conta:
    def __init__(self, numero, titular, saldo=0.0):
        self._numero = numero
        self._titular = titular
        self._saldo = saldo

    def deposita(self, valor):
        if valor < 0:
            raise ValueError('Você tentou depositar um valor negativo.')
        self._saldo += valor

    def saca(self, valor):
        if valor < 0:
            raise ValueError('Você tentou sacar um valor negativo.')
        if self._saldo < valor:
            raise SaldoInsuficienteError('Saldo insuficiente.')
        self._saldo -= valor

    def get_saldo(self):
        return self._saldo

class ContaCorrente(Conta):
    def saca(self, valor):
        if valor < 0:
            raise ValueError('Você tentou sacar um valor negativo.')
        if self._saldo < valor + 0.10:
            raise SaldoInsuficienteError('Saldo insuficiente.')
        self._saldo -= (valor + 0.10)

class ContaPoupanca(Conta):
    def deposita(self, valor):
        if valor < 0:
            raise ValueError('Você tentou depositar um valor negativo.')
        self._saldo += valor

if __name__ == '__main__':
    cc_marcos = ContaCorrente('101', 'Marcos Silva', 1000.0)

    print("\n[ Marcos ]")
    try:
        cc_marcos.saca(-100.0)
    except ValueError:
        print('O valor a ser sacado deve ser um número positivo.')

    try:
        cc_marcos.saca(2000.0)
    except ValueError:
        print('O valor a ser sacado deve ser um número positivo.')
    except SaldoInsuficienteError:
        print('Você não possui saldo suficiente para concluir esta operação.')

    try:
        cc_marcos.deposita(-500.0)
    except ValueError:
        print('O valor a ser depositado deve ser um número positivo.')

    cc_ana = ContaCorrente('102', 'Ana Paula', 1500.0)

    print("\n[ Ana ]")
    try:
        cc_ana.saca(1400.0)
        print(f'Saldo restante de Ana: R${cc_ana.get_saldo():.2f}')
    except Exception as e:
        print(f'Erro: {e}')

    cp_joao = ContaPoupanca('103', 'João Carlos', 500.0)

    print("\n[ João ]")
    try:
        cp_joao.deposita(-100)
    except ValueError:
        print('O valor a ser depositado deve ser um número positivo.')

    try:
        cp_joao.saca(700)
    except SaldoInsuficienteError:
        print('Você não possui saldo suficiente para concluir esta operação.')