# -*- coding: utf-8 -*-
"""atividade 8.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_-O2d6AvEL5SVnoPwI-dTJjrKBAvchaa
"""



import os
import subprocess

os.makedirs('oo', exist_ok=True)

codigo_conta = '''class Conta:

    def __init__(self, numero, titular, saldo, limite):
        self.numero = numero
        self.titular = titular
        self.saldo = saldo
        self.limite = limite

    def deposita(self, valor):
        self.saldo += valor

    def saca(self, valor):
        if self.saldo < valor:
            return False
        else:
            self.saldo -= valor
            return True

    def extrato(self):
        print("numero: {} \\nsaldo: {}".format(self.numero, self.saldo))

    def transfere_para(self, destino, valor):
        retirou = self.saca(valor)
        if not retirou:
            return False
        else:
            destino.deposita(valor)
            return True
'''

with open('oo/conta.py', 'w') as f:
    f.write(codigo_conta)

codigo_teste = '''from conta import Conta

conta1 = Conta('123-4', 'Carlos', 120.0, 1000.0)
conta2 = Conta('567-8', 'Ana', 200.0, 1000.0)

conta1.deposita(50.0)
conta1.extrato()

conta1.saca(20.0)
conta1.extrato()

sucesso = conta1.transfere_para(conta2, 100.0)
print("Transferência realizada?", sucesso)

conta1.extrato()
conta2.extrato()
'''

with open('oo/conta_teste.py', 'w') as f:
    f.write(codigo_teste)

subprocess.run(['python3', 'oo/conta_teste.py'])