# -*- coding: utf-8 -*-
"""atividade 12.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_-O2d6AvEL5SVnoPwI-dTJjrKBAvchaa
"""

class TributavelMixIn:
    def get_valor_imposto(self):
        pass

class Conta:
    def __init__(self, numero, titular, saldo=0.0):
        self._numero = numero
        self._titular = titular
        self._saldo = saldo

    def deposita(self, valor):
        self._saldo += valor

    def saca(self, valor):
        self._saldo -= valor

    def get_saldo(self):
        return self._saldo

class ContaCorrente(Conta, TributavelMixIn):
    def get_valor_imposto(self):
        return self._saldo * 0.01

class SeguroDeVida(TributavelMixIn):
    def __init__(self, valor, titular, numero_apolice):
        self._valor = valor
        self._titular = titular
        self._numero_apolice = numero_apolice

    def get_valor_imposto(self):
        return 50 + self._valor * 0.05

class ManipuladorDeTributaveis:
    def calcula_impostos(self, lista_tributaveis):
        total = 0
        for t in lista_tributaveis:
            total += t.get_valor_imposto()
        return total

if __name__ == '__main__':
    cc1 = ContaCorrente('100', 'Carlos Silva', 1500.0)
    cc2 = ContaCorrente('200', 'Ana Pereira', 2500.0)
    seguro1 = SeguroDeVida(150.0, 'Ana Pereira', '555-66')
    seguro2 = SeguroDeVida(300.0, 'Lucas Mendes', '777-88')

    lista_tributaveis = [cc1, cc2, seguro1, seguro2]

    manipulador = ManipuladorDeTributaveis()
    total = manipulador.calcula_impostos(lista_tributaveis)

    print(f"Total de impostos: R${total:.2f}")